spring.application.name=ecommerce-backend


spring.security.user.name=admin
spring.security.user.password=admin


spring.datasource.url=jdbc:mysql://localhost:3306/niorra_ecommerce
spring.datasource.username=root
spring.datasource.password=MosesEvan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.jackson.serialization.indent_output=true